# SciPy
These are improved Numpy functions

In [12]:
from scipy import constants
from scipy.sparse.csgraph import floyd_warshall, depth_first_order, breadth_first_order, connected_components
from scipy.sparse import csr_matrix
import numpy as np

##### SciPy Constants


In [ ]:
print(constants.pi)
print(constants.pico)

##### Constant Units
The *dir()* function can be used to view a list of all units in the constants module

In [4]:
print(dir(constants))

['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_codata', '_constants', '_obsolete_constants', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_ratio', 'grain', '

# SciPy Graphs
### Floyd Warshall
The **floyd_warshall()** function is used to find the shortest path between each pair of component by using the floyd Warshall technic

In [7]:
arr = np.array([
    [0, 1, 2],
    [1, 0, 0],
    [2, 0, 0]    
])

newarr = csr_matrix(arr)
print(floyd_warshall(newarr, return_predecessors=True))

(array([[0., 1., 2.],
       [1., 0., 3.],
       [2., 3., 0.]]), array([[-9999,     0,     0],
       [    1, -9999,     0],
       [    2,     0, -9999]]))


##### Depth First Order
A depth traversal from a node is returned by **depth_first_order()** method

In [9]:
arr = np.array([
    [0, 1, 0, 1],
    [1, 1, 1, 1],
    [2, 1, 1, 0],
    [0, 1, 0, 1]
]) 
newarr = csr_matrix(arr)
print(depth_first_order(newarr, 1))

(array([1, 0, 3, 2]), array([    1, -9999,     1,     0]))


##### Breadth First Order
The **breadth_first_order()** method returns a breadth first traversal from a node.

In [11]:
arr = np.array([
    [0, 1, 0, 1],
    [1, 1, 1, 1],
    [2, 1, 1, 0],
    [0, 1, 0, 1]
]) 
newarr = csr_matrix(arr)
print(breadth_first_order(newarr, 1))

(array([1, 0, 2, 3]), array([    1, -9999,     1,     1]))


##### Connected Components
To find all the connected components, the **connected_components()** method is used.